### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by Scoi4101** [IBM-Security/isam-ansible-roles#17]
**Reporting Stuff is awesome**

get_junction_details -> Please allow us to provide the inputs to see the details

Use Case: Create / Mod a Junction, then show the updates after its complete

**Comment by ram-ibm** [comment]
The get_junction_details role took a bit of effort since it is reading a rather complicated data structure created from two previous calls.

Maybe it might make more sense to create a new role when you can get details for one junction. I am not clear how you would use it in a playbook though for your use case... do you want to dump the data from a junction after you call set_junction role?

It is easy to add a role, hoping the conventions I have used is simple to follow. Do you want to try that out and see if you can flesh out your use case?

**Comment by Scoi4101** [comment]
Thats exactly our use case

Create it
Show it

I will create a role and see how it works thanks
