### ISSUE TITLE
add_oauth_client 

### ISSUE THREAD

**Issue by ramraj241** [IBM-Security/isam-ansible-roles#188]
Is there a role to add multiple redirect uris? the one which is available right now add_oauth_client is updating the current redirect uri instead of adding new one

**Comment by ram-ibm** [comment]
I would start by using set() instead of add(). I recollect redirect uris can be multiples - but REST API documentation is showing a string:
https://www.ibm.com/support/knowledgecenter/SSPREK_9.0.7/com.ibm.isam.doc/develop/rapi/Register%20an%20API%20protection%20client.xml

May need to check how the LMI is doing it and use the corresponding type (perhaps list when updating it).

**Comment by ramraj241** [comment]
I tried a custom role with set() and it still does the same action as add()...just replacing/overwriting the existing stuff...any other ways to get this redirurls added?

**Comment by ram-ibm** [comment]
Try passing data like this:

```
add_oauth_client_redirectUri:
  - "/firstRedirect"
  - "/secondRedirect"
```

You need to pass an array of values to redirectUri. If it is still not working, please provide sample data that is not working for you.

**Comment by ramraj241** [comment]
That works, thanks Ram
